DROP DATABASE IF EXISTS lootjes;
DROP TABLE IF EXISTS Deelnemers;
DROP TABLE IF EXISTS Groep;
DROP TABLE IF EXISTS Oprichter;

CREATE DATABASE lootjes;

CREATE TABLE Groep (
    GroepId INT NOT NULL AUTO_INCREMENT,
    Naam VARCHAR(255) NOT NULL,
    Bedrag INTEGER NULL,
    Datum INT,
    PRIMARY KEY(GroepId)
);

CREATE TABLE Deelnemers (
    DeelnemerId INT NOT NULL AUTO_INCREMENT,
    GroepId INT,
    Naam VARCHAR(255),
    Postcode VARCHAR(6),
    PRIMARY KEY(DeelnemerId),
    FOREIGN KEY(GroepId) REFERENCES Groep(GroepId)
);

CREATE TABLE Oprichter (
    OprichterId INT NOT NULL AUTO_INCREMENT,
    Naam VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Bericht VARCHAR(255)
    PRIMARY KEY(OprichterId)
);